development: &defaults
  client_id: 628120630579374
  client_secret: 96f764738d755c05fd6fd2888f7c4def
  scope: email,publish_stream
  canvas_url: http://figoeyewear.com/facebook


test:
  <<: *defaults

staging:
  <<: *defaults
  client_id: 628120630579374
  client_secret: 96f764738d755c05fd6fd2888f7c4def
  scope: email,publish_stream
  canvas_url: http://figoeyewear.com/facebook
  
production:
  client_id: 721083471238678
  client_secret: fc52b3680a5d2541c09dee14b1b5dade
  scope: email,publish_stream
  canvas_url: http://figoeyewear.com/facebook
