development: &defaults
  client_id: 611050205604591
  client_secret: 866b0a561496266acb45f047055894a3
  scope: email,publish_stream #,user_about_me,friends_about_me,user_activities,friends_activities,user_birthday,friends_birthday,user_checkins,friends_checkins,user_education_history,friends_education_history,user_events,friends_events,user_groups,friends_groups,user_hometown,friends_hometown,user_interests,friends_interests,user_likes,friends_likes,user_location,friends_location,user_notes,friends_notes,user_online_presence,friends_online_presence,user_photo_video_tags,friends_photo_video_tags,user_photos,friends_photos,user_questions,friends_questions,user_relationships,friends_relationships,user_relationship_details,friends_relationship_details,user_religion_politics,friends_religion_politics,user_status,friends_status,user_videos,friends_videos,user_website,friends_website,user_work_history,friends_work_history,email,read_friendlists,read_insights,read_mailbox,read_requests,read_stream,xmpp_login,ads_management,create_event,manage_friendlists,manage_notifications,offline_access,publish_checkins,publish_stream,rsvp_event,publish_actions,manage_pages,user_subscriptions,friend_subscriptions
  canvas_url: http://localhost:3000/

test:
  <<: *defaults

staging:
  <<: *defaults
  client_id: 628120630579374
  client_secret: 96f764738d755c05fd6fd2888f7c4def
  scope: email,publish_stream
  canvas_url: http://figoeyewear.com/facebook
  
production:
  client_id: 721083471238678
  client_secret: fc52b3680a5d2541c09dee14b1b5dade
  scope: email,publish_stream
  canvas_url: http://figoeyewear.com/facebook
